name: iris_classifier
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.0
  - scikit-learn>=1.3
  - altair>=5.0
  - jupyterlab>=4.0
  - notebook>=7.0
  - ipykernel
  - numpy
  - requests
  - pandera>=0.18





